### ISSUE TITLE
编辑商品的时候，怎么给每一个单元格设置之前保存的价格值

### ISSUE THREAD

**Issue by w-hehe** [sc1992sc/vue-sku-table#1]

**Comment by sc1992sc** [comment]
v-model绑定的值传进去就好了。如下图就是v-model="skus"，设置skus就可以回显设置
![image](https://user-images.githubusercontent.com/12607664/219566800-4963de93-2f30-4edd-8f06-250ff693674c.png)

**Comment by w-hehe** [comment]
我在动态变更商品规格时，sku表格是否可以同时动态变化

**Comment by w-hehe** [comment]
我在动态push > specs > values属性时，发现deep无法深度监听到这个属性值的变化

**Comment by sc1992sc** [comment]
规格id应该是固定的吧，为啥是动态的，不同的id应该算是不同的规格了吧

**Comment by w-hehe** [comment]
> v-model绑定的值传进去就好了。如下图就是v-model="skus"，设置skus就可以回显设置 ![image](https://user-images.githubusercontent.com/12607664/219566800-4963de93-2f30-4edd-8f06-250ff693674c.png)

大佬，留个联系方式，有偿求指导。我搞不出来

**Comment by sc1992sc** [comment]
微信号:scflyer

**Comment by sc1992sc** [comment]
> > v-model绑定的值传进去就好了。如下图就是v-model="skus"，设置skus就可以回显设置 ![image](https://user-images.githubusercontent.com/12607664/219566800-4963de93-2f30-4edd-8f06-250ff693674c.png)
> 
> 大佬，留个联系方式，有偿求指导。我搞不出来

微信号:scflyer
